# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Run black

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/black.yml"
      - "bin/*.py"
      - "bin/pyproject.toml"

  pull_request:
    paths:
      - ".github/workflows/black.yml"
      - "bin/*.py"
      - "bin/pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run black
        uses: psf/black@stable
        with:
          src: bin/
          jupyter: true
